#!/usr/bin/env python3
#
# Crude check that Package.swift does not enable 'useLocalDSPHeaders' in Package.swift' file --
# doing so can break the CI build since there will not be a DSPHeaders repo installed locally.
# A more sound approach would be to write the check in Swift.

import sys
import re

pat = re.compile('^let *useLocalDSPHeaders *= true')

if __name__ == '__main__':
    if 'Package.swift' in sys.argv:
        with open('Package.swift') as fd:
            for line in fd.readlines():
                if pat.match(line):
                    print('** FOUND:', line)
                    sys.exit(1)
    sys.exit(0)
