name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build, test, and code coverage
      run: make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: dbe62f18182c82eb36dc1030819bc54b
        filename: SF2Lib-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
