name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcoe 15.4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: Build, test, and code coverage
      run: make
    - name: Get Test Coverage
      run: |
        set -- $(< percentage.txt)
        echo "PERCENTAGE=${1}" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: dbe62f18182c82eb36dc1030819bc54b
        filename: SF2Lib-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
