name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode Xcode_26.0.1
      run: ls -l /Applications && sudo xcode-select -s /Applications/Xcode_26.0.1.app
    - name: Build, test, and code coverage
      run: make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: dbe62f18182c82eb36dc1030819bc54b
        filename: SF2Lib-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
